apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: renancavalcantercb/ebs:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secrets
