name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy manifests to server
        run: |
          scp -r ./k8s/ backend-secrets.yaml renanserv@192.168.1.18:/home/renanserv/ecommerce-infra/

      - name: Apply Kubernetes manifests on server
        run: |
          ssh renanserv@192.168.1.18 << 'EOF'
            kubectl apply -f /home/renanserv/ecommerce-infra/k8s/backend/backend-secrets.yaml
            kubectl apply -f /home/renanserv/ecommerce-infra/k8s/
          EOF
