name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or Update Kubernetes Secrets
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          kubectl create secret generic backend-secrets \
            --namespace=ecommerce \
            --from-literal=SECRET_KEY="${SECRET_KEY}" \
            --from-literal=MONGO_URI="${MONGO_URI}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          cd k8s/scripts && ./deploy.sh
